//
// Created by tta on 01/12/2021.
//

#ifndef SIMPLERENDERENGINEPROJECT_OBJECTTYPE_HPP
#define SIMPLERENDERENGINEPROJECT_OBJECTTYPE_HPP

enum ObjectType {AsteroidLarge, AsteroidMedium, AsteroidSmall};

#endif //SIMPLERENDERENGINEPROJECT_OBJECTTYPE_HPP
