//
// Created by tta on 01/12/2021.
//

#ifndef SIMPLERENDERENGINEPROJECT_SOUNDENUM_HPP
#define SIMPLERENDERENGINEPROJECT_SOUNDENUM_HPP

enum SoundEnum {AsteroidExplosion, SpaceshipExplosion, Shooting};

#endif //SIMPLERENDERENGINEPROJECT_SOUNDENUM_HPP
